- generic [active] [ref=e1]:
  - generic [ref=e2]:
    - main [ref=e3]:
      - navigation "Main" [ref=e6]:
        - generic [ref=e7]:
          - link "Oasis of Change" [ref=e9] [cursor=pointer]:
            - /url: index.html
            - img "Oasis of Change" [ref=e10]
          - list [ref=e11]:
            - listitem [ref=e12]:
              - link "Home" [ref=e13] [cursor=pointer]:
                - /url: index.html
            - listitem [ref=e14]:
              - link "Initiatives" [ref=e15] [cursor=pointer]:
                - /url: initiatives.html
                - generic [ref=e16]:
                  - generic [ref=e17]: Initiatives
                  - img [ref=e18]
            - listitem [ref=e20]:
              - link "Case Studies" [ref=e21] [cursor=pointer]:
                - /url: case-studies.html
            - listitem [ref=e22]:
              - link "Company" [ref=e23] [cursor=pointer]:
                - /url: company.html
                - generic [ref=e24]:
                  - generic [ref=e25]: Company
                  - img [ref=e26]
            - listitem [ref=e28]:
              - link "Blog" [ref=e29] [cursor=pointer]:
                - /url: blog/
          - generic [ref=e30]:
            - button "EN" [ref=e32] [cursor=pointer]:
              - img [ref=e33]
              - generic [ref=e35]: EN
              - img [ref=e36]
            - link "Get Involved" [ref=e38] [cursor=pointer]:
              - /url: get_involved.html
              - generic [ref=e39]: Get Involved
              - img [ref=e40]
      - generic [ref=e43]:
        - generic [ref=e44]:
          - navigation "Breadcrumb" [ref=e45]:
            - link "Home" [ref=e46] [cursor=pointer]:
              - /url: index.html
            - text: / For Nonprofits
          - generic [ref=e47]:
            - generic [ref=e48]:
              - generic [ref=e49]: Partnerships
              - heading "We partner with other nonprofits" [level=1] [ref=e51]:
                - text: We partner with
                - text: other nonprofits
              - paragraph [ref=e52]: Web-Ready helps nonprofits strengthen their digital presence with donated technology, lower-impact websites, and practical accessibility improvements.
            - generic [ref=e54]:
              - paragraph [ref=e55]: Quick start
              - paragraph [ref=e56]: Tell us what you need
              - generic [ref=e57]:
                - link "Request nonprofit support" [ref=e58] [cursor=pointer]:
                  - /url: contact.html?type=nonprofit
                - link "Explore Web-Ready" [ref=e59] [cursor=pointer]:
                  - /url: web-ready.html
        - generic [ref=e60]:
          - paragraph [ref=e61]: Who this is for
          - paragraph [ref=e62]: Nonprofits, charities, and community organizations that want stronger tools, a simpler website, and a better experience for everyone.
        - generic [ref=e63]:
          - generic [ref=e65]:
            - paragraph [ref=e66]: Web-Ready support
            - heading "How we can help" [level=2] [ref=e67]
          - generic [ref=e68]:
            - generic [ref=e69]:
              - generic [ref=e71]: "01"
              - heading "Nonprofit technology grants" [level=3] [ref=e73]
              - list [ref=e74]:
                - listitem [ref=e75]: Find in-kind grants and donated tools
                - listitem [ref=e76]: Get set up with accounts, access, and basics
                - listitem [ref=e77]: Reduce overhead while improving capacity
              - link "Ask about grants" [ref=e78] [cursor=pointer]:
                - /url: contact.html?type=nonprofit-grants
                - text: Ask about grants
                - img [ref=e79]
            - generic [ref=e81]:
              - generic [ref=e83]: "02"
              - heading "Lower energy, faster pages" [level=3] [ref=e85]
              - list [ref=e86]:
                - listitem [ref=e87]: Improve performance and reduce page weight
                - listitem [ref=e88]: Lower carbon, energy, and data transfer
                - listitem [ref=e89]: Keep the design modern and reliable
              - link "See results" [ref=e90] [cursor=pointer]:
                - /url: case-studies.html
                - text: See results
                - img [ref=e91]
            - generic [ref=e93]:
              - generic [ref=e95]: "03"
              - heading "Easier to use for everyone" [level=3] [ref=e97]
              - list [ref=e98]:
                - listitem [ref=e99]: Clear structure, headings, and navigation
                - listitem [ref=e100]: Better contrast, forms, and keyboard support
                - listitem [ref=e101]: Improved experience with assistive tech
              - link "Accessibility approach" [ref=e102] [cursor=pointer]:
                - /url: accessibility_statement.html
                - text: Accessibility approach
                - img [ref=e103]
        - generic [ref=e106]:
          - generic [ref=e107]:
            - paragraph [ref=e108]: What to expect
            - heading "A simple, nonprofit-friendly workflow" [level=2] [ref=e109]
            - paragraph [ref=e110]: We start with your goals, then focus on the few changes that make the biggest difference.
          - generic [ref=e112]:
            - generic [ref=e113]:
              - generic [ref=e114]: "1"
              - paragraph [ref=e115]: Share your needs
              - paragraph [ref=e116]: "Tell us what you need: grants, performance, accessibility, or all three."
            - generic [ref=e117]:
              - generic [ref=e118]: "2"
              - paragraph [ref=e119]: Get a clear plan
              - paragraph [ref=e120]: We propose what we'll do, why it matters, and what changes you'll see.
            - generic [ref=e121]:
              - generic [ref=e122]: "3"
              - paragraph [ref=e123]: Implement and improve
              - paragraph [ref=e124]: We make the changes and help you keep improving over time.
        - generic [ref=e126]:
          - generic [ref=e127]:
            - paragraph [ref=e128]: Next step
            - heading "Let's support your mission" [level=2] [ref=e129]
            - paragraph [ref=e130]: Tell us what you're working toward and where you need help. We'll connect you with the right support.
            - generic [ref=e131]:
              - link "Contact us" [ref=e132] [cursor=pointer]:
                - /url: contact.html?type=nonprofit
              - link "Explore the WRA Platform" [ref=e133] [cursor=pointer]:
                - /url: wra_platform.html
          - generic [ref=e134]:
            - paragraph [ref=e135]: Already exploring?
            - generic [ref=e136]:
              - link "View case studies" [ref=e137] [cursor=pointer]:
                - /url: case-studies.html
                - generic [ref=e138]: View case studies
                - img [ref=e139]
              - link "Sustainability statement" [ref=e141] [cursor=pointer]:
                - /url: sustainability_statement.html
                - generic [ref=e142]: Sustainability statement
                - img [ref=e143]
              - link "Impact dashboard" [ref=e145] [cursor=pointer]:
                - /url: https://impact.oasisofchange.com
                - generic [ref=e146]: Impact dashboard
                - img [ref=e147]
    - contentinfo [ref=e149]:
      - generic [ref=e150]:
        - generic [ref=e151]:
          - generic [ref=e152]:
            - img "Oasis of Change" [ref=e154]
            - paragraph [ref=e155]: Building a more sustainable digital future through energy-efficient websites, transparent impact, and technology that supports communities and the planet.
            - generic "Based in Vancouver, Canada" [ref=e156]:
              - generic [ref=e157]: Based in Vancouver, Canada
              - img [ref=e158]
          - navigation "Footer" [ref=e163]:
            - generic [ref=e164]:
              - paragraph [ref=e165]: General
              - list [ref=e166]:
                - listitem [ref=e167]:
                  - link "Home" [ref=e168] [cursor=pointer]:
                    - /url: index.html
                - listitem [ref=e169]:
                  - link "Get Involved" [ref=e170] [cursor=pointer]:
                    - /url: get_involved.html
                - listitem [ref=e171]:
                  - link "For Nonprofits" [ref=e172] [cursor=pointer]:
                    - /url: nonprofits.html
                - listitem [ref=e173]:
                  - link "Blog" [ref=e174] [cursor=pointer]:
                    - /url: blog/
                - listitem [ref=e175]:
                  - link "Case Studies" [ref=e176] [cursor=pointer]:
                    - /url: case-studies.html
                - listitem [ref=e177]:
                  - link "Contact" [ref=e178] [cursor=pointer]:
                    - /url: contact.html
            - generic [ref=e179]:
              - paragraph [ref=e180]: Initiatives
              - list [ref=e181]:
                - listitem [ref=e182]:
                  - link "Web-Ready" [ref=e183] [cursor=pointer]:
                    - /url: web-ready.html
                - listitem [ref=e184]:
                  - link "Vancouver Centre for AI Safety, Sustainability, and Ethics (VCASSE)" [ref=e185] [cursor=pointer]:
                    - /url: vcasse.html
                - listitem [ref=e186]:
                  - link "Sustainable Technology Week" [ref=e187] [cursor=pointer]:
                    - /url: sustainable-technology-week.html
                - listitem [ref=e188]:
                  - link "WRA Platform" [ref=e189] [cursor=pointer]:
                    - /url: wra_platform.html
            - generic [ref=e190]:
              - paragraph [ref=e191]: Company
              - list [ref=e192]:
                - listitem [ref=e193]:
                  - link "Our Story" [ref=e194] [cursor=pointer]:
                    - /url: about.html
                - listitem [ref=e195]:
                  - link "Our Mission" [ref=e196] [cursor=pointer]:
                    - /url: about.html#OurMission
                - listitem [ref=e197]:
                  - link "Our Founder" [ref=e198] [cursor=pointer]:
                    - /url: gabriel-dalton.html
                - listitem [ref=e199]:
                  - link "Our Board" [ref=e200] [cursor=pointer]:
                    - /url: about.html#our-board
                - listitem [ref=e201]:
                  - link "Annual Reports" [ref=e202] [cursor=pointer]:
                    - /url: annual_reports.html
                - listitem [ref=e203]:
                  - link "News / Press" [ref=e204] [cursor=pointer]:
                    - /url: news_release.html
            - generic [ref=e205]:
              - paragraph [ref=e206]: Accountability
              - list [ref=e207]:
                - listitem [ref=e208]:
                  - link "Impact Dashboard" [ref=e209] [cursor=pointer]:
                    - /url: https://impact.oasisofchange.com
                - listitem [ref=e210]:
                  - link "Sustainability Statement" [ref=e211] [cursor=pointer]:
                    - /url: sustainability_statement.html
                - listitem [ref=e212]:
                  - link "Tree Planting Statement" [ref=e213] [cursor=pointer]:
                    - /url: tree_planting.html
                - listitem [ref=e214]:
                  - link "Accessibility Statement" [ref=e215] [cursor=pointer]:
                    - /url: accessibility_statement.html
                - listitem [ref=e216]:
                  - link "Privacy Policy" [ref=e217] [cursor=pointer]:
                    - /url: privacy-policy.html
        - paragraph [ref=e219]: © 2026 Oasis of Change, Inc. All rights reserved.
  - img [ref=e222]